source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Use CocoaPods 1.16+ for Ruby 3.4 compatibility
gem 'cocoapods', '~> 1.16'
gem 'activesupport', '>= 6.1.7.5', '< 8.0.0'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'
gem 'ostruct'
gem 'base64'
gem 'nkf'
