ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'OptimizeSampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # AEP Swift tweaks + workaround for emitted module interface verification
    installer.pods_project.targets.each do |target|
      if target.name.start_with?('AEP')
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
          config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
          config.build_settings['SWIFT_EMIT_MODULE_INTERFACE'] = 'NO'
          config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -no-verify-emitted-module-interface'
        end
      end

      if target.name == 'RCTAEPCore'
        target.build_configurations.each do |config|
          config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited)'
          config.build_settings['HEADER_SEARCH_PATHS'] += ' "$(PODS_ROOT)/../build/generated/ios/ReactCodegen"'
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -fcxx-modules'
        end
      end
    end
  end
end
